openapi: 3.1.0
x-stoplight:
  id: i8i3l2jkf1i6e
info:
  title: timmew
  version: '1.0'
  description: 'https://timmew.commew.net で利用するREST API'
servers:
  - url: 'http://localhost:5757'
    description: local
paths:
  /accounts:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              examples:
                ExampleSuccess:
                  value:
                    id: 1
                    name: NekoKoneko
                    openIdProvider:
                      - sub: '10769150350006150715113082367'
                        provider: google
      operationId: getAccounts
      description: アカウントを1件取得する。アカウントの識別子はAuthorizationに指定したJWT形式のトークンの物が利用される。
      parameters: []
      security:
        - Authorization: []
    post:
      summary: ''
      operationId: postAccounts
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
              examples:
                ExampleSuccess:
                  value:
                    id: 1
                    name: NekoKoneko
                    openIdProvider:
                      - sub: '10769150350006150715113082367'
                        provider: google
            application/xml:
              schema:
                type: object
                properties: {}
      description: アカウント登録を行うAPI
      parameters:
        - schema:
            type: string
            example: Basic YWRtaW5Vc2VyOnBhc3N3b3JkMTIzNA==
          in: header
          name: Authorization
          description: 'Authorization: Basic の形で送信する'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenIdProvider'
            examples:
              Example 1:
                value:
                  sub: '10769150350006150715113082367'
                  provider: google
        description: ''
components:
  schemas:
    Account:
      title: account
      x-stoplight:
        id: d81ba26a96905
      type: object
      description: アカウント
      examples:
        - id: 1
          name: NekoKoneko
          openIdProvider:
            - sub: '10769150350006150715113082367'
              provider: google
        - id: 2
          name: MyCat
          openIdProvider:
            - sub: '999999999999999999999999999'
              provider: google
            - sub: lineid99999999999999999999999
              provider: line
      properties:
        id:
          type: number
          minimum: 1
          description: アカウントの識別子
        name:
          type: string
          description: アカウント名
        openIdProviders:
          type: array
          items:
            $ref: '#/components/schemas/OpenIdProvider'
      required:
        - id
        - name
        - openIdProviders
    OpenIdProvider:
      title: OpenIdProvider
      x-stoplight:
        id: e1ambjwj1ixhm
      type: object
      description: 登録・ログイン時に利用するOpenIdProvider
      properties:
        sub:
          type: string
          example: '10769150350006150715113082367'
          description: OpenIdProviderのユーザー識別子
        provider:
          type: string
          pattern: /^(google|line|apple|facebook)$/
          description: 'OpenIdProviderの種類を表す .e.g. google, line'
      required:
        - sub
        - provider
      examples:
        - sub: '10769150350006150715113082367'
          provider: google
        - sub: lineid99999999999999999999999
          provider: line
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      description: Bearer + 半角スペース + JWT形式のトークンで指定する。
